//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_GLF_OPF {
        displayName = "Global Liberation Front";
        side = 0;
        flag = "po_main\data\UI\flags\flag_ua_co.paa";
        icon = "po_main\data\UI\flags\flag_ua_co.paa";
        priority = 0;
    };
};