//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class min_rf_soldier;
    class min_rf_soldier_OCimport_01 : min_rf_soldier { scope = 0; class EventHandlers; };
    class min_rf_soldier_OCimport_02 : min_rf_soldier_OCimport_01 { class EventHandlers; };

    class min_rf_spetsnaz;
    class min_rf_spetsnaz_OCimport_01 : min_rf_spetsnaz { scope = 0; class EventHandlers; };
    class min_rf_spetsnaz_OCimport_02 : min_rf_spetsnaz_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_M;
    class min_rf_soldier_M_OCimport_01 : min_rf_soldier_M { scope = 0; class EventHandlers; };
    class min_rf_soldier_M_OCimport_02 : min_rf_soldier_M_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_AR;
    class min_rf_soldier_AR_OCimport_01 : min_rf_soldier_AR { scope = 0; class EventHandlers; };
    class min_rf_soldier_AR_OCimport_02 : min_rf_soldier_AR_OCimport_01 { class EventHandlers; };

    class min_rf_medic;
    class min_rf_medic_OCimport_01 : min_rf_medic { scope = 0; class EventHandlers; };
    class min_rf_medic_OCimport_02 : min_rf_medic_OCimport_01 { class EventHandlers; };

    class min_rf_engineer;
    class min_rf_engineer_OCimport_01 : min_rf_engineer { scope = 0; class EventHandlers; };
    class min_rf_engineer_OCimport_02 : min_rf_engineer_OCimport_01 { class EventHandlers; };

    class min_rf_officer;
    class min_rf_officer_OCimport_01 : min_rf_officer { scope = 0; class EventHandlers; };
    class min_rf_officer_OCimport_02 : min_rf_officer_OCimport_01 { class EventHandlers; };

    class min_rf_spetsnaz_TL;
    class min_rf_spetsnaz_TL_OCimport_01 : min_rf_spetsnaz_TL { scope = 0; class EventHandlers; };
    class min_rf_spetsnaz_TL_OCimport_02 : min_rf_spetsnaz_TL_OCimport_01 { class EventHandlers; };


    class O_GLF_Rifleman_AKM_OPF_01 : min_rf_soldier_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist (AKM)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_TTsKO";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_04","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_04","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{},{"CUP_U_O_Partisan_TTsKO",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_762x39_AK47_M",6,30}}},{},"CUP_H_C_Ushanka_04","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_AKS_74_OPF_01 : O_GLF_Rifleman_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist (AKS-74)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_VSR_Mixed1";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_02","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_02","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_Partisan_VSR_Mixed1",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_545x39_AK_M",8,30}}},{},"CUP_H_C_Ushanka_02","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_AK_105_OPF_01 : O_GLF_Rifleman_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist (AK-105)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_VSR_Mixed2";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK105","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK105","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK105","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_U_O_Partisan_VSR_Mixed2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{},"CUP_H_C_Ushanka_03","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Winter_Terrorist_AUGA1_OPF_01 : min_rf_spetsnaz_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Winter Terrorist (AUGA1)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_33";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AUG_A1","","","",{"CUP_30Rnd_556x45_AUG",30},{},""},{},{},{"CUP_I_B_PMC_Unit_33",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_556x45_AUG",8,30}}},{},"","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_SVD_OPF_01 : min_rf_soldier_M_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist (SVD)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_TTsKO_Mixed";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_01","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_01","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_SVD","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_SVD","Rangefinder"};

        magazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};
        respawnMagazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_SVD","","","CUP_optic_PSO_3",{"CUP_10Rnd_762x54_SVD_M",10},{},""},{},{},{"CUP_U_O_Partisan_TTsKO_Mixed",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_10Rnd_762x54_SVD_M",8,10}}},{},"CUP_H_C_Ushanka_01","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_M82A1_OPF_01 : O_GLF_Terrorist_SVD_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist (M82A1)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_TTsKO_Mixed";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_01","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_01","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_M107_Base","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_M107_Base","Rangefinder"};

        magazines[] = {"CUP_10Rnd_127x99_M107","CUP_10Rnd_127x99_M107"};
        respawnMagazines[] = {"CUP_10Rnd_127x99_M107","CUP_10Rnd_127x99_M107"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M107_Base","","","CUP_optic_LeupoldM3LR",{"CUP_10Rnd_127x99_M107",10},{},""},{},{},{"CUP_U_O_Partisan_TTsKO_Mixed",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_10Rnd_127x99_M107",4,10}}},{},"CUP_H_C_Ushanka_01","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_RPK_74_OPF_01 : min_rf_soldier_AR_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist (RPK-74)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_VSR_Mixed2";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_MG","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_MG","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_RPK74_45","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_RPK74_45","Rangefinder"};

        magazines[] = {"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M","CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"};
        respawnMagazines[] = {"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M","CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_RPK74_45","","","",{"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",45},{},""},{},{},{"CUP_U_O_Partisan_VSR_Mixed2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_MG",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",6,45}}},{},"CUP_H_C_Ushanka_03","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_Medic_AKS_74_OPF_01 : min_rf_medic_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist Medic (AKS-74)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_TTsKO";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_Partisan_TTsKO",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_545x39_AK_M",8,30}}},{"rhs_assault_umbts",{{"ACE_morphine",40},{"ACE_tourniquet",4},{"ACE_epinephrine",40},{"ACE_elasticBandage",40},{"ACE_bloodIV_500",10},{"ACE_bloodIV",6},{"ACE_bloodIV_250",2}}},"CUP_H_C_Ushanka_03","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_Engineer_AKS_74_OPF_01 : min_rf_engineer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist Engineer (AKS-74)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "CUP_U_O_Partisan_TTsKO_Mixed";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_04","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_04","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK105","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK105","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "rhs_assault_umbts_engineer_empty";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK105","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_U_O_Partisan_TTsKO_Mixed",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{"rhs_assault_umbts_engineer_empty",{{"MineDetector",1},{"ACE_Clacker",1},{"ACE_EntrenchingTool",1},{"ACE_DefusalKit",1},{"SatchelCharge_Remote_Mag",2,1},{"DemoCharge_Remote_Mag",2,1}}},"CUP_H_C_Ushanka_04","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Terrorist_Leader_OPF_01 : min_rf_officer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terrorist Leader";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Orange_EOD","LanguageRUS_F"};

        uniformClass = "CUP_U_C_Pilot_01";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Com","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Com","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{},{"CUP_U_C_Pilot_01",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Com",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_762x39_AK47_M",6,30}}},{},"CUP_H_C_Ushanka_03","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Winter_Bomb_Maker_OPF_01 : min_rf_spetsnaz_TL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Winter Bomb Maker";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Tanker","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_34";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK105","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK105","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "rhs_assault_umbts_engineer_empty";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK105","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_I_B_PMC_Unit_34",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1},{"CUP_30Rnd_545x39_AK74M_M",2,30}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_545x39_AK74M_M",8,30}}},{"rhs_assault_umbts_engineer_empty",{{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_Clacker",1},{"MineDetector",1},{"DemoCharge_Remote_Mag",2,1},{"SatchelCharge_Remote_Mag",2,1}}},"","G_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Winter_Triggerman_OPF_01 : min_rf_spetsnaz_TL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Winter Triggerman";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Orange_Civilian","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_33";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_I_B_PMC_Unit_33",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1},{"CUP_30Rnd_545x39_AK_M",2,30}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_Clacker",2},{"ACE_M26_Clacker",2},{"ACE_DeadManSwitch",2},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_545x39_AK_M",6,30}}},{},"","G_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Arms_Dealer_OPF_01 : O_GLF_Terrorist_Leader_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Arms Dealer";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Orange_Officer","LanguageRUS_F"};

        uniformClass = "CUP_U_O_TK_Green";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig_Light","CUP_H_C_Ushanka_03","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{},{"CUP_U_O_TK_Green",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_O_Ins_Carrier_Rig_Light",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",3,1},{"SmokeShell",4,1},{"CUP_30Rnd_762x39_AK47_M",6,30}}},{},"CUP_H_C_Ushanka_03","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_GLF_Infiltrator_AK_105_OPF_01 : O_GLF_Rifleman_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Infiltrator (AK-105)";
        side = 0;
        faction = "O_GLF_OPF";

        identityTypes[] = {"Head_Russian","LanguageRUS_F"};

        uniformClass = "U_C_ArtTShirt_01_v6_F";

        linkedItems[] = {"ItemWatch"};
        respawnlinkedItems[] = {"ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_CivilianBackpack_01_Everyday_Black_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_ArtTShirt_01_v6_F",{{"ACE_elasticBandage",5},{"ACE_morphine",5},{"ACE_personalAidKit",1}}},{},{"B_CivilianBackpack_01_Everyday_Black_F",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ItemCompass",1},{"ItemGPS",1},{"ItemMap",1},{"rhs_mag_rgd5",3,1},{"rhs_30Rnd_545x39_7N10_AK",7,30},{"SmokeShell",4,1},{{"rhs_weap_ak105_folded","rhs_acc_pgs64","","",{},{},""},1},{{"Rangefinder","","","",{},{},""},1},{"CUP_V_O_Ins_Carrier_Rig_Light",false}}},"","",{},{"","","","","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};