//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class O_APF_OPF {
            name = "Arabic Patriotic Front";

            class Infantry {
                name = "Infantry";

                class o_apf_infantry_infantry_squad_opf {
                    name = "Infantry Squad";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_APF_Squad_Leader_GP25_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AKM_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AK_101_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AK_101_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_RPG7_OPF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Autorifleman_RPK_74_OPF_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Marksman_SVD_OPF_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Medic_AKS_74_OPF_01";
                    };
                };

                class o_apf_infantry_lmg_team_opf {
                    name = "LMG Team";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AK_101_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AKM_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Autorifleman_RPK_74_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Autorifleman_RPK_74_OPF_01";
                    };
                };

                class o_apf_infantry_marksman_team_opf {
                    name = "Marksman Team";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AK_101_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AKM_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Marksman_SVD_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Marksman_SVD_OPF_01";
                    };
                };

                class o_apf_infantry_at_team_opf {
                    name = "AT Team";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AK_101_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AKM_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_RPG7_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_RPG7_OPF_01";
                    };
                };

                class o_apf_infantry_sentry_opf {
                    name = "Sentry";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AK_101_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Rifleman_AKM_OPF_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class o_apf_infantry_elite_guard_squad_opf {
                    name = "Elite Guard Squad";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Machine_Gunner_PKP_OPF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Machine_Gunner_PKP_OPF_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Marksman_M82A1_OPF_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Marksman_M82A1_OPF_01";
                    };
                };

                class o_apf_specops_elite_guard_gpmg_team_opf {
                    name = "Elite Guard GPMG Team";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Machine_Gunner_PKP_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Machine_Gunner_PKP_OPF_01";
                    };
                };

                class o_apf_specops_elite_guard_marksman_team_opf {
                    name = "Elite Guard Marksman Team";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Marksman_M82A1_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Marksman_M82A1_OPF_01";
                    };
                };

                class o_apf_specops_elite_guard_sentry_opf {
                    name = "Elite Guard Sentry";
                    side = 0;
                    faction = "O_APF_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_APF_Elite_Guardsman_OTs_14_OPF_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};