//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LOP_TKA_Infantry_Rifleman;
    class LOP_TKA_Infantry_Rifleman_OCimport_01 : LOP_TKA_Infantry_Rifleman { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Rifleman_OCimport_02 : LOP_TKA_Infantry_Rifleman_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Rifleman_2;
    class LOP_TKA_Infantry_Rifleman_2_OCimport_01 : LOP_TKA_Infantry_Rifleman_2 { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Rifleman_2_OCimport_02 : LOP_TKA_Infantry_Rifleman_2_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Rifleman_3;
    class LOP_TKA_Infantry_Rifleman_3_OCimport_01 : LOP_TKA_Infantry_Rifleman_3 { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Rifleman_3_OCimport_02 : LOP_TKA_Infantry_Rifleman_3_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_GL;
    class LOP_TKA_Infantry_GL_OCimport_01 : LOP_TKA_Infantry_GL { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_GL_OCimport_02 : LOP_TKA_Infantry_GL_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_MG;
    class LOP_TKA_Infantry_MG_OCimport_01 : LOP_TKA_Infantry_MG { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_MG_OCimport_02 : LOP_TKA_Infantry_MG_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Marksman;
    class LOP_TKA_Infantry_Marksman_OCimport_01 : LOP_TKA_Infantry_Marksman { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Marksman_OCimport_02 : LOP_TKA_Infantry_Marksman_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Corpsman;
    class LOP_TKA_Infantry_Corpsman_OCimport_01 : LOP_TKA_Infantry_Corpsman { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Corpsman_OCimport_02 : LOP_TKA_Infantry_Corpsman_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Crewman;
    class LOP_TKA_Infantry_Crewman_OCimport_01 : LOP_TKA_Infantry_Crewman { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Crewman_OCimport_02 : LOP_TKA_Infantry_Crewman_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Pilot;
    class LOP_TKA_Infantry_Pilot_OCimport_01 : LOP_TKA_Infantry_Pilot { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Pilot_OCimport_02 : LOP_TKA_Infantry_Pilot_OCimport_01 { class EventHandlers; };

    class LOP_TKA_Infantry_Officer;
    class LOP_TKA_Infantry_Officer_OCimport_01 : LOP_TKA_Infantry_Officer { scope = 0; class EventHandlers; };
    class LOP_TKA_Infantry_Officer_OCimport_02 : LOP_TKA_Infantry_Officer_OCimport_01 { class EventHandlers; };

    class O_recon_F;
    class O_recon_F_OCimport_01 : O_recon_F { scope = 0; class EventHandlers; };
    class O_recon_F_OCimport_02 : O_recon_F_OCimport_01 { class EventHandlers; };

    class O_recon_M_F;
    class O_recon_M_F_OCimport_01 : O_recon_M_F { scope = 0; class EventHandlers; };
    class O_recon_M_F_OCimport_02 : O_recon_M_F_OCimport_01 { class EventHandlers; };


    class O_APF_Rifleman_AKM_OPF_01 : LOP_TKA_Infantry_Rifleman_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AKM)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_bakelite_M",30},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_762x39_AK47_bakelite_M",8,30}}},{},"CUP_H_Ger_M92","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Rifleman_AK_101_OPF_01 : LOP_TKA_Infantry_Rifleman_2_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AK-101)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK101","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK101","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AK","CUP_30Rnd_556x45_AK"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AK","CUP_30Rnd_556x45_AK"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK101","","","",{"CUP_30Rnd_556x45_AK",30},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_556x45_AK",7,30}}},{},"CUP_H_Ger_M92","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Rifleman_RPG7_OPF_01 : LOP_TKA_Infantry_Rifleman_3_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (RPG7)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK101","CUP_launch_RPG7V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK101","CUP_launch_RPG7V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AK","CUP_PG7V_M","CUP_30Rnd_556x45_AK"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AK","CUP_PG7V_M","CUP_30Rnd_556x45_AK"};

        backpack = "CUP_B_RPGPack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK101","","","",{"CUP_30Rnd_556x45_AK",30},{},""},{"CUP_launch_RPG7V","","","",{"CUP_PG7V_M",1},{},""},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_556x45_AK",7,30}}},{"CUP_B_RPGPack_Khaki",{{"rhs_rpg7_PG7V_mag",5,1}}},"CUP_H_Ger_M92_GG_CF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Squad_Leader_GP25_OPF_01 : LOP_TKA_Infantry_GL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader (GP25)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92_GG","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92_GG","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74_GL_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74_GL_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74_GL_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_545x39_AK_M",7,30},{"CUP_1Rnd_HE_GP25_M",5,1}}},{},"CUP_H_Ger_M92_GG","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Autorifleman_RPK_74_OPF_01 : LOP_TKA_Infantry_MG_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman (RPK-74)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_AR","CUP_H_Ger_M92","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_AR","CUP_H_Ger_M92","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_RPK74_45","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_RPK74_45","Rangefinder"};

        magazines[] = {"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M","CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"};
        respawnMagazines[] = {"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M","CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"};

        backpack = "CUP_B_AlicePack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_RPK74_45","","","",{"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",45},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_AR",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",8,45}}},{"CUP_B_AlicePack_Khaki",{{"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",30,45}}},"CUP_H_Ger_M92","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Marksman_SVD_OPF_01 : LOP_TKA_Infantry_Marksman_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman (SVD)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_FR_BandanaGreen","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_FR_BandanaGreen","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_SVD","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_SVD","Rangefinder"};

        magazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};
        respawnMagazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_SVD","","","CUP_optic_PSO_3",{"CUP_10Rnd_762x54_SVD_M",10},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_10Rnd_762x54_SVD_M",9,10}}},{},"CUP_H_FR_BandanaGreen","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Medic_AKS_74_OPF_01 : LOP_TKA_Infantry_Corpsman_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic (AKS-74)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92_GG_CB","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","CUP_H_Ger_M92_GG_CB","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        backpack = "CUP_B_AlicePack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_545x39_AK_M",9,30}}},{"CUP_B_AlicePack_Khaki",{{"ACE_epinephrine",50},{"ACE_elasticBandage",50},{"ACE_morphine",50},{"ACE_tourniquet",5},{"ACE_bloodIV_500",10},{"ACE_bloodIV",9},{"ACE_bloodIV_250",2}}},"CUP_H_Ger_M92_GG_CB","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Crewman_AKS_74U_OPF_01 : LOP_TKA_Infantry_Crewman_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman (AKS-74U)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_COM","CUP_H_RUS_TSH_4_Brown","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_COM","CUP_H_RUS_TSH_4_Brown","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74U","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_COM",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_545x39_AK74_plum_M",4,30}}},{},"CUP_H_RUS_TSH_4_Brown","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Pilot_AKS_74U_OPF_01 : LOP_TKA_Infantry_Pilot_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot (AKS-74U)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_RUS_M88_MSV";

        linkedItems[] = {"BRM_IBA_GREEN_COM","CUP_H_RUS_ZSH_Shield_Up","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_COM","CUP_H_RUS_ZSH_Shield_Up","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74U","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"CUP_U_O_RUS_M88_MSV",{{"ACE_personalAidKit",1},{"ACE_morphine",15},{"ACE_epinephrine",10},{"ACE_elasticBandage",17},{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"BRM_IBA_GREEN_COM",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_545x39_AK74_plum_M",4,30}}},{},"CUP_H_RUS_ZSH_Shield_Up","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Field_Commander_OPF_01 : LOP_TKA_Infantry_Officer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Field Commander";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Orange_Officer","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_TK_Green";

        linkedItems[] = {"RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_M17_Black","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_M17_Black","Rangefinder"};

        magazines[] = {"CUP_17Rnd_9x19_M17_Black","CUP_17Rnd_9x19_M17_Black"};
        respawnMagazines[] = {"CUP_17Rnd_9x19_M17_Black","CUP_17Rnd_9x19_M17_Black"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M17_Black","","","",{"CUP_17Rnd_9x19_M17_Black",17},{},""},{"CUP_U_O_TK_Green",{{"CUP_17Rnd_9x19_M17_Black",6,17}}},{},{},"RMS37_Beret_APF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Colonel_OPF_01 : O_APF_Field_Commander_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Colonel";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Orange_FIA","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_TK_Officer";

        linkedItems[] = {"RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_TaurusTracker455","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_TaurusTracker455","Rangefinder"};

        magazines[] = {"CUP_6Rnd_45ACP_M","CUP_6Rnd_45ACP_M"};
        respawnMagazines[] = {"CUP_6Rnd_45ACP_M","CUP_6Rnd_45ACP_M"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_TaurusTracker455","","","",{"CUP_6Rnd_45ACP_M",6},{},""},{"CUP_U_O_TK_Officer",{{"CUP_6Rnd_45ACP_M",5,6}}},{},{},"RMS37_Beret_APF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Elite_Guardsman_OTs_14_OPF_01 : O_recon_F_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Elite Guardsman (OTs-14)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_TK_Green";

        linkedItems[] = {"BRM_IBA_GREEN_RFL","RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_RFL","RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_OTS14_GROZA_762_Grip","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_OTS14_GROZA_762_Grip","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_OTS14_GROZA_762_Grip","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{},{"CUP_U_O_TK_Green",{{"ACE_personalAidKit",1},{"ACE_morphine",10},{"ACE_epinephrine",10},{"CUP_30Rnd_762x39_AK47_M",1,30}}},{"BRM_IBA_GREEN_RFL",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",3,1},{"CUP_30Rnd_762x39_AK47_M",7,30}}},{},"RMS37_Beret_APF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Elite_Machine_Gunner_PKP_OPF_01 : O_recon_F_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Elite Machine Gunner (PKP)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_TK_Green";

        linkedItems[] = {"BRM_IBA_GREEN_MG","RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_MG","RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_Pecheneg_B50_vfg","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_Pecheneg_B50_vfg","Rangefinder"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};

        backpack = "CUP_B_AlicePack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_Pecheneg_B50_vfg","","","",{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",100},{},""},{},{},{"CUP_U_O_TK_Green",{{"ACE_personalAidKit",1},{"ACE_morphine",10},{"ACE_epinephrine",10}}},{"BRM_IBA_GREEN_MG",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",2,1},{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",2,100}}},{"CUP_B_AlicePack_Khaki",{{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",6,100}}},"RMS37_Beret_APF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_APF_Elite_Marksman_M82A1_OPF_01 : O_recon_M_F_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Elite Marksman (M82A1)";
        side = 0;
        faction = "O_APF_OPF";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_O_TK_Green";

        linkedItems[] = {"BRM_IBA_GREEN_MG","RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_IBA_GREEN_MG","RMS37_Beret_APF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_M107_Base","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_M107_Base","Rangefinder"};

        magazines[] = {"CUP_10Rnd_127x99_M107","CUP_10Rnd_127x99_M107"};
        respawnMagazines[] = {"CUP_10Rnd_127x99_M107","CUP_10Rnd_127x99_M107"};

        backpack = "B_LegStrapBag_olive_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M107_Base","","","CUP_optic_LeupoldM3LR",{"CUP_10Rnd_127x99_M107",10},{},""},{},{},{"CUP_U_O_TK_Green",{{"ACE_personalAidKit",1},{"ACE_morphine",10},{"ACE_epinephrine",10}}},{"BRM_IBA_GREEN_MG",{{"rhs_mag_rdg2_white",4,1},{"rhs_mag_rgd5",2,1},{"CUP_10Rnd_127x99_M107",6,10}}},{"B_LegStrapBag_olive_F",{{"CUP_10Rnd_127x99_M107",5,10}}},"RMS37_Beret_APF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};