//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_UNWDL_IND {
        displayName = "United Nations (NATO Woodland)";
        side = 2;
        flag = "ca\Ca_E\data\flag_uno_co.paa";
        icon = "ca\Ca_E\data\flag_uno_co.paa";
        priority = 0;
    };
};