//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_RACS_IND {
        displayName = "Royal Army Corps of Sahrani (NATO Backed)";
        side = 2;
        flag = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_racs_co";
        icon = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_racs_co";
        priority = 0;
    };
};