//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_RACS_IND {
            name = "Royal Army Corps of Sahrani (NATO Backed)";

            class Infantry {
                name = "Infantry";

                class i_racs_infantry_infantry_squad_ind {
                    name = "Infantry Squad";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_RACS_Squad_Leader_SCAR_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_AT_IND_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Grenadier_EGLM_IND_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Marksman_HK417_IND_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Autorifleman_Mk46_IND_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Combat_Life_Saver_SCAR_IND_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Engineer_SCAR_IND_01";
                    };
                };

                class i_racs_infantry_lmg_team_ind {
                    name = "LMG Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Autorifleman_Mk46_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Autorifleman_Mk46_IND_01";
                    };
                };

                class i_racs_infantry_gpmg_team_ind {
                    name = "GPMG Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Assistant_240B_Gunner_SCAR_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Machine_Gunner_M240B_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Assistant_240B_Gunner_SCAR_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Machine_Gunner_M240B_IND_01";
                    };
                };

                class i_racs_infantry_marksman_team_ind {
                    name = "Marksman Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Marksman_HK417_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Marksman_HK417_IND_01";
                    };
                };

                class i_racs_infantry_at_team_ind {
                    name = "AT Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_AT_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_AT_IND_01";
                    };
                };

                class i_racs_infantry_grenadier_team_ind {
                    name = "Grenadier Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Grenadier_EGLM_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Grenadier_EGLM_IND_01";
                    };
                };

                class i_racs_infantry_sentry_ind {
                    name = "Sentry";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Rifleman_SCAR_IND_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class i_racs_specops_royal_guard_squad_ind {
                    name = "Royal Guard Squad";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Autorifleman_XM8_SAW_IND_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Autorifleman_XM8_SAW_IND_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Sharpshooter_M107_IND_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Sharpshooter_M107_IND_01";
                    };
                };

                class i_racs_specops_royal_guard_lmg_team_ind {
                    name = "Royal Guard LMG Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Autorifleman_XM8_SAW_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Autorifleman_XM8_SAW_IND_01";
                    };
                };

                class i_racs_specops_royal_guard_marksman_team_ind {
                    name = "Royal Guard Marksman Team";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Sharpshooter_M107_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Sharpshooter_M107_IND_01";
                    };
                };

                class i_racs_specops_royal_guard_sentry_ind {
                    name = "Royal Guard Sentry";
                    side = 2;
                    faction = "I_RACS_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_RACS_Royal_Guardsman_XM8_IND_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};