//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_CLWHMR_IND {
        displayName = "Clawhammer Industries";
        side = 2;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\LivoniaLooters_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\LivoniaLooters_CA.paa";
        priority = 0;
    };
};