//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_CLWHMR_IND {
            name = "Clawhammer Industries";

            class Infantry {
                name = "Infantry";

                class i_clwhmr_infantry_mercenary_squad_ind {
                    name = "Mercenary Squad";
                    side = 2;
                    faction = "I_CLWHMR_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_EGLM_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_Medic_CTAR_21_IND_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_Engineer_CTAR_21_IND_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_SR_25_IND_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_MG36_IND_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_SMAW_IND_01";
                    };
                };

                class i_clwhmr_infantry_lmg_team_ind {
                    name = "LMG Team";
                    side = 2;
                    faction = "I_CLWHMR_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_MG36_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_MG36_IND_01";
                    };
                };

                class i_clwhmr_infantry_marksman_team_ind {
                    name = "Marksman Team";
                    side = 2;
                    faction = "I_CLWHMR_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_SR_25_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_SR_25_IND_01";
                    };
                };

                class i_clwhmr_infantry_at_team_ind {
                    name = "AT Team";
                    side = 2;
                    faction = "I_CLWHMR_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_SMAW_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_SMAW_IND_01";
                    };
                };

                class i_clwhmr_infantry_sentry_ind {
                    name = "Sentry";
                    side = 2;
                    faction = "I_CLWHMR_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_CLWHMR_Mercenary_TAR_21_IND_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};