//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class CUP_I_PMC_Soldier;
    class CUP_I_PMC_Soldier_OCimport_01 : CUP_I_PMC_Soldier { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Soldier_OCimport_02 : CUP_I_PMC_Soldier_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Soldier_AT;
    class CUP_I_PMC_Soldier_AT_OCimport_01 : CUP_I_PMC_Soldier_AT { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Soldier_AT_OCimport_02 : CUP_I_PMC_Soldier_AT_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Soldier_MG;
    class CUP_I_PMC_Soldier_MG_OCimport_01 : CUP_I_PMC_Soldier_MG { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Soldier_MG_OCimport_02 : CUP_I_PMC_Soldier_MG_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Sniper_KSVK;
    class CUP_I_PMC_Sniper_KSVK_OCimport_01 : CUP_I_PMC_Sniper_KSVK { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Sniper_KSVK_OCimport_02 : CUP_I_PMC_Sniper_KSVK_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Soldier_GL;
    class CUP_I_PMC_Soldier_GL_OCimport_01 : CUP_I_PMC_Soldier_GL { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Soldier_GL_OCimport_02 : CUP_I_PMC_Soldier_GL_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Medic;
    class CUP_I_PMC_Medic_OCimport_01 : CUP_I_PMC_Medic { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Medic_OCimport_02 : CUP_I_PMC_Medic_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Engineer;
    class CUP_I_PMC_Engineer_OCimport_01 : CUP_I_PMC_Engineer { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Engineer_OCimport_02 : CUP_I_PMC_Engineer_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Crew;
    class CUP_I_PMC_Crew_OCimport_01 : CUP_I_PMC_Crew { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Crew_OCimport_02 : CUP_I_PMC_Crew_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Pilot;
    class CUP_I_PMC_Pilot_OCimport_01 : CUP_I_PMC_Pilot { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Pilot_OCimport_02 : CUP_I_PMC_Pilot_OCimport_01 { class EventHandlers; };

    class CUP_I_PMC_Soldier_TL;
    class CUP_I_PMC_Soldier_TL_OCimport_01 : CUP_I_PMC_Soldier_TL { scope = 0; class EventHandlers; };
    class CUP_I_PMC_Soldier_TL_OCimport_02 : CUP_I_PMC_Soldier_TL_OCimport_01 { class EventHandlers; };


    class I_CLWHMR_Mercenary_TAR_21_IND_01 : CUP_I_PMC_Soldier_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (TAR-21)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_mas_idf_TRG21_F","Rangefinder"};
        respawnWeapons[] = {"arifle_mas_idf_TRG21_F","Rangefinder"};

        magazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};
        respawnMagazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_mas_idf_TRG21_F","","","CUP_optic_MARS",{"30Rnd_mas_idf_556x45sd_Stanag",30},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"rhs_mag_30Rnd_556x45_M855_Stanag",7,30}}},{},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_SMAW_IND_01 : CUP_I_PMC_Soldier_AT_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (SMAW)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_mas_idf_TRG21_F","CUP_launch_Mk153Mod0","Rangefinder"};
        respawnWeapons[] = {"arifle_mas_idf_TRG21_F","CUP_launch_Mk153Mod0","Rangefinder"};

        magazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","CUP_SMAW_HEAA_M","30Rnd_mas_idf_556x45sd_Stanag"};
        respawnMagazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","CUP_SMAW_HEAA_M","30Rnd_mas_idf_556x45sd_Stanag"};

        backpack = "min_rf_torna_black";

        ALiVE_orbatCreator_loadout[] = {{"arifle_mas_idf_TRG21_F","","","CUP_optic_MARS",{"30Rnd_mas_idf_556x45sd_Stanag",30},{},""},{"CUP_launch_Mk153Mod0","","","",{"CUP_SMAW_HEAA_M",1},{},""},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"rhs_mag_30Rnd_556x45_M855_Stanag",7,30}}},{"min_rf_torna_black",{{"CUP_SMAW_HEAA_M",3,1}}},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_MG36_IND_01 : CUP_I_PMC_Soldier_MG_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (MG36)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_AR","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_AR","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36A","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_G36A","Rangefinder"};

        magazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_100Rnd_556x45_BetaCMag"};
        respawnMagazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_100Rnd_556x45_BetaCMag"};

        backpack = "min_rf_torna_black";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36A","","","CUP_optic_G36Optics15x_3D",{"CUP_100Rnd_556x45_BetaCMag",100},{},"CUP_Bipod_G36"},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_AR",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"CUP_100Rnd_556x45_BetaCMag",3,100},{"CUP_30Rnd_556x45_G36",1,30}}},{"min_rf_torna_black",{{"CUP_100Rnd_556x45_BetaCMag",16,100}}},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_SR_25_IND_01 : CUP_I_PMC_Sniper_KSVK_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (SR-25)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_m110_kac_black","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_m110_kac_black","Rangefinder"};

        magazines[] = {"CUP_20Rnd_762x51_B_M110","CUP_20Rnd_762x51_B_M110"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_B_M110","CUP_20Rnd_762x51_B_M110"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_m110_kac_black","CUP_muzzle_snds_M110_black","","CUP_optic_LeupoldM3LR",{"CUP_20Rnd_762x51_B_M110",20},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"CUP_20Rnd_762x51_B_M110",5,20}}},{"B_LegStrapBag_black_F",{{"CUP_20Rnd_762x51_B_M110",5,20}}},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_EGLM_IND_01 : CUP_I_PMC_Soldier_GL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (EGLM)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_Euro","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_mas_idf_TRG21_GL_F","Rangefinder"};
        respawnWeapons[] = {"arifle_mas_idf_TRG21_GL_F","Rangefinder"};

        magazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};
        respawnMagazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_mas_idf_TRG21_GL_F","","","CUP_optic_MARS",{"30Rnd_mas_idf_556x45sd_Stanag",30},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"rhs_mag_30Rnd_556x45_M855_Stanag",5,30},{"1Rnd_HE_Grenade_shell",6,1}}},{"B_LegStrapBag_black_F",{{"1Rnd_HE_Grenade_shell",5,1},{"rhs_mag_30Rnd_556x45_M855_Stanag",6,30}}},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_Medic_CTAR_21_IND_01 : CUP_I_PMC_Medic_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (Medic CTAR-21)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_mas_idf_TRG20_F","Rangefinder"};
        respawnWeapons[] = {"arifle_mas_idf_TRG20_F","Rangefinder"};

        magazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};
        respawnMagazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};

        backpack = "min_rf_torna_black";

        ALiVE_orbatCreator_loadout[] = {{"arifle_mas_idf_TRG20_F","","","CUP_optic_MARS",{"30Rnd_mas_idf_556x45sd_Stanag",30},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"rhs_mag_30Rnd_556x45_M855_Stanag",7,30}}},{"min_rf_torna_black",{{"ACE_tourniquet",6},{"ACE_morphine",52},{"ACE_epinephrine",50},{"ACE_elasticBandage",52},{"ACE_bloodIV_500",16},{"ACE_bloodIV",7},{"ACE_bloodIV_250",4}}},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_Engineer_CTAR_21_IND_01 : CUP_I_PMC_Engineer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (Engineer CTAR-21)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"arifle_mas_idf_TRG20_F","Rangefinder"};
        respawnWeapons[] = {"arifle_mas_idf_TRG20_F","Rangefinder"};

        magazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};
        respawnMagazines[] = {"30Rnd_mas_idf_556x45sd_Stanag","30Rnd_mas_idf_556x45sd_Stanag"};

        backpack = "min_rf_torna_black";

        ALiVE_orbatCreator_loadout[] = {{"arifle_mas_idf_TRG20_F","","","CUP_optic_MARS",{"30Rnd_mas_idf_556x45sd_Stanag",30},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"rhs_mag_30Rnd_556x45_M855_Stanag",7,30}}},{"min_rf_torna_black",{{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_Clacker",1},{"MineDetector",1},{"SatchelCharge_Remote_Mag",2,1},{"DemoCharge_Remote_Mag",6,1}}},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_Crew_P90_IND_01 : CUP_I_PMC_Crew_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (Crew P90)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","H_Tank_black_F","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","H_Tank_black_F","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_p90_black","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_p90_black","Rangefinder"};

        magazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};
        respawnMagazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_p90_black","","","",{"50Rnd_570x28_SMG_03",50},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Empty",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"50Rnd_570x28_SMG_03",1,50}}},{"B_LegStrapBag_black_F",{{"50Rnd_570x28_SMG_03",6,50}}},"H_Tank_black_F","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Mercenary_Pilot_P90_IND_01 : CUP_I_PMC_Pilot_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (Pilot P90)";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","rhsusf_hgu56p_visor_black","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","rhsusf_hgu56p_visor_black","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_p90_black","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_p90_black","Rangefinder"};

        magazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};
        respawnMagazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_p90_black","","","",{"50Rnd_570x28_SMG_03",50},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Empty",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"50Rnd_570x28_SMG_03",1,50}}},{"B_LegStrapBag_black_F",{{"50Rnd_570x28_SMG_03",6,50}}},"rhsusf_hgu56p_visor_black","CUP_G_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Leader_IND_01 : CUP_I_PMC_Soldier_TL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Leader";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Orange_FIA","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_Deagle","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_Deagle","Rangefinder"};

        magazines[] = {"CUP_7Rnd_50AE_Deagle","CUP_7Rnd_50AE_Deagle"};
        respawnMagazines[] = {"CUP_7Rnd_50AE_Deagle","CUP_7Rnd_50AE_Deagle"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_Deagle","","","",{"CUP_7Rnd_50AE_Deagle",7},{},""},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Empty",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"CUP_7Rnd_50AE_Deagle",1,7}}},{"B_LegStrapBag_black_F",{{"CUP_7Rnd_50AE_Deagle",11,7}}},"RMS37_Beret_Clawhammer","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CLWHMR_Second_in_Command_IND_01 : CUP_I_PMC_Soldier_TL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Second in Command";
        side = 2;
        faction = "I_CLWHMR_IND";

        identityTypes[] = {"Orange_Civilian","LanguageENG_F","CUP_G_ARMY"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_AR","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_AR","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36A","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_G36A","Rangefinder"};

        magazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_100Rnd_556x45_BetaCMag"};
        respawnMagazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_100Rnd_556x45_BetaCMag"};

        backpack = "min_rf_torna_black";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36A","","","CUP_optic_G36Optics15x_3D",{"CUP_100Rnd_556x45_BetaCMag",100},{},"CUP_Bipod_G36"},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_AR",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"CUP_100Rnd_556x45_BetaCMag",3,100},{"CUP_30Rnd_556x45_G36",1,30}}},{"min_rf_torna_black",{{"CUP_100Rnd_556x45_BetaCMag",16,100}}},"RMS37_Beret_Clawhammer","G_Aviator",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};