//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_UNDES_IND {
            name = "United Nations (NATO Desert)";

            class Infantry {
                name = "Infantry";

                class i_undes_infantry_peacekeeper_squad_ind {
                    name = "Peacekeeper Squad";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_UNDES_Squad_Leader_L85_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M16A4_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_L85_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_G36_IND_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_HK417_IND_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M249_IND_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Medic_G36_IND_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Engineer_CZ805_IND_01";
                    };
                };

                class i_undes_infantry_lmg_team_ind {
                    name = "LMG Team";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M16A4_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M16A4_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M249_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M249_IND_01";
                    };
                };

                class i_undes_infantry_marksman_team_ind {
                    name = "Marksman Team";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_L85_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_L85_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_HK417_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_HK417_IND_01";
                    };
                };

                class i_undes_infantry_doctor_team_ind {
                    name = "Doctor Team";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_G36_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_G36_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Medic_G36_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Medic_G36_IND_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Doctor_Glock_17_IND_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_G36_IND_01";
                    };
                };

                class i_undes_infantry_sentry_ind {
                    name = "Sentry";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_M16A4_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_L85_IND_01";
                    };
                };

                class i_undes_infantry_cbrn_team_ind {
                    name = "CBRN Team";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                };

                class i_undes_infantry_cbrn_sentry_ind {
                    name = "CBRN Sentry";
                    side = 2;
                    faction = "I_UNDES_IND";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_UNDES_Peacekeeper_CBRN_CZ805_IND_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};