//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_SLA_OPF {
        displayName = "Sahrani Liberation Army ";
        side = 0;
        flag = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_sla_co";
        icon = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_sla_co";
        priority = 0;
    };
};