//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class O_SLA_OPF {
            name = "Sahrani Liberation Army ";

            class Infantry {
                name = "Infantry";

                class o_sla_infantry_infantry_squad_opf {
                    name = "Infantry Squad";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Grenadier_GP_25_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_74_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_103_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AKM_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_74_OPF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_RPG_OPF_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Marksman_SVD_OPF_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Autorifleman_RPK_OPF_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Medic_AKS_74_OPF_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Engineer_AKS_74_OPF_01";
                    };
                };

                class o_sla_infantry_lmg_team_opf {
                    name = "LMG Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_74_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_103_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Autorifleman_RPK_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Autorifleman_RPK_OPF_01";
                    };
                };

                class o_sla_infantry_gpmg_team_opf {
                    name = "GPMG Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Assistant_PKM_Gunner_AKS_74_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Machine_Gunner_PKM_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Assistant_PKM_Gunner_AKS_74_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Machine_Gunner_PKM_OPF_01";
                    };
                };

                class o_sla_infantry_marksman_team_opf {
                    name = "Marksman Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_74_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_103_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Marksman_SVD_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Marksman_SVD_OPF_01";
                    };
                };

                class o_sla_infantry_at_team_opf {
                    name = "AT Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_74_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_103_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_RPG_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_RPG_OPF_01";
                    };
                };

                class o_sla_infantry_sentry_opf {
                    name = "Sentry";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_74_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_103_OPF_01";
                    };
                };

                class o_sla_infantry_company_hq_opf {
                    name = "Company HQ";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 0;
                        vehicle = "O_SLA_Field_Officer_PP_19_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_SLA_Grenadier_GP_25_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_RPG_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Medic_AKS_74_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Engineer_AKS_74_OPF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Machine_Gunner_PKM_OPF_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Marksman_SVD_OPF_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Rifleman_AK_103_OPF_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class o_sla_infantry_especas_squad_opf {
                    name = "Especas Squad";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Grenadier_GP_25_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Especas_Marksman_L115_OPF_01";
                    };
                    class Unit5 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                };

                class o_sla_specops_especas_gpmg_team_opf {
                    name = "Especas GPMG Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Especas_Machine_Gunner_PKP_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Especas_Machine_Gunner_PKP_OPF_01";
                    };
                };

                class o_sla_specops_especas_marksman_team_opf {
                    name = "Especas Marksman Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Especas_Marksman_L115_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_SLA_Especas_Marksman_L115_OPF_01";
                    };
                };

                class o_sla_specops_especas_sentry_opf {
                    name = "Especas Sentry";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                };

                class o_sla_specops_especas_protection_team_opf {
                    name = "Especas General Protection Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Grenadier_GP_25_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                    class Unit4 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                    class Unit5 {
                        position[] = {-5,-15,0};
                        rank = "COLONEL";
                        side = 0;
                        vehicle = "O_SLA_General_OPF_01";
                    };
                };

                class o_sla_specops_especas_arms_dealer_protection_team_opf {
                    name = "Especas Arms Dealer Protection Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Grenadier_GP_25_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "MAJOR";
                        side = 0;
                        vehicle = "O_SLA_Arms_Dealer_OPF_01";
                    };
                };

                class o_sla_specops_especas_propagandist_team_opf {
                    name = "Especas Propagandist Team";
                    side = 0;
                    faction = "O_SLA_OPF";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Grenadier_GP_25_OPF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_SLA_Especas_Rifleman_AK_74M_OPF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_SLA_Especas_Medic_AK_74M_OPF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "MAJOR";
                        side = 0;
                        vehicle = "O_SLA_Propagandist_OPF_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};