//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class min_rf_soldier;
    class min_rf_soldier_OCimport_01 : min_rf_soldier { scope = 0; class EventHandlers; };
    class min_rf_soldier_OCimport_02 : min_rf_soldier_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_LAT;
    class min_rf_soldier_LAT_OCimport_01 : min_rf_soldier_LAT { scope = 0; class EventHandlers; };
    class min_rf_soldier_LAT_OCimport_02 : min_rf_soldier_LAT_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_GL;
    class min_rf_soldier_GL_OCimport_01 : min_rf_soldier_GL { scope = 0; class EventHandlers; };
    class min_rf_soldier_GL_OCimport_02 : min_rf_soldier_GL_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_M;
    class min_rf_soldier_M_OCimport_01 : min_rf_soldier_M { scope = 0; class EventHandlers; };
    class min_rf_soldier_M_OCimport_02 : min_rf_soldier_M_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_AR;
    class min_rf_soldier_AR_OCimport_01 : min_rf_soldier_AR { scope = 0; class EventHandlers; };
    class min_rf_soldier_AR_OCimport_02 : min_rf_soldier_AR_OCimport_01 { class EventHandlers; };

    class min_rf_medic;
    class min_rf_medic_OCimport_01 : min_rf_medic { scope = 0; class EventHandlers; };
    class min_rf_medic_OCimport_02 : min_rf_medic_OCimport_01 { class EventHandlers; };

    class min_rf_engineer;
    class min_rf_engineer_OCimport_01 : min_rf_engineer { scope = 0; class EventHandlers; };
    class min_rf_engineer_OCimport_02 : min_rf_engineer_OCimport_01 { class EventHandlers; };

    class min_rf_crew;
    class min_rf_crew_OCimport_01 : min_rf_crew { scope = 0; class EventHandlers; };
    class min_rf_crew_OCimport_02 : min_rf_crew_OCimport_01 { class EventHandlers; };

    class min_rf_pilot;
    class min_rf_pilot_OCimport_01 : min_rf_pilot { scope = 0; class EventHandlers; };
    class min_rf_pilot_OCimport_02 : min_rf_pilot_OCimport_01 { class EventHandlers; };

    class min_rf_officer;
    class min_rf_officer_OCimport_01 : min_rf_officer { scope = 0; class EventHandlers; };
    class min_rf_officer_OCimport_02 : min_rf_officer_OCimport_01 { class EventHandlers; };

    class min_rf_spetsnaz;
    class min_rf_spetsnaz_OCimport_01 : min_rf_spetsnaz { scope = 0; class EventHandlers; };
    class min_rf_spetsnaz_OCimport_02 : min_rf_spetsnaz_OCimport_01 { class EventHandlers; };

    class min_rf_spetsnaz_AR;
    class min_rf_spetsnaz_AR_OCimport_01 : min_rf_spetsnaz_AR { scope = 0; class EventHandlers; };
    class min_rf_spetsnaz_AR_OCimport_02 : min_rf_spetsnaz_AR_OCimport_01 { class EventHandlers; };

    class min_rf_spetsnaz_GL;
    class min_rf_spetsnaz_GL_OCimport_01 : min_rf_spetsnaz_GL { scope = 0; class EventHandlers; };
    class min_rf_spetsnaz_GL_OCimport_02 : min_rf_spetsnaz_GL_OCimport_01 { class EventHandlers; };

    class min_rf_spetsnaz_M;
    class min_rf_spetsnaz_M_OCimport_01 : min_rf_spetsnaz_M { scope = 0; class EventHandlers; };
    class min_rf_spetsnaz_M_OCimport_02 : min_rf_spetsnaz_M_OCimport_01 { class EventHandlers; };

    class min_rf_recon_medic;
    class min_rf_recon_medic_OCimport_01 : min_rf_recon_medic { scope = 0; class EventHandlers; };
    class min_rf_recon_medic_OCimport_02 : min_rf_recon_medic_OCimport_01 { class EventHandlers; };


    class O_SLA_Rifleman_AKM_OPF_01 : min_rf_soldier_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AKM)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_762x39_AK47_M",6,30}}},{},"CUP_H_Ger_M92_RGR","CUP_G_ESS_BLK",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Rifleman_AK_74_OPF_01 : O_SLA_Rifleman_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AK-74)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{},"CUP_H_Ger_M92_RGR_GG_CF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Rifleman_AK_103_OPF_01 : O_SLA_Rifleman_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AK-103)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK103","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK103","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK103_bakelite_M","CUP_30Rnd_762x39_AK103_bakelite_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK103_bakelite_M","CUP_30Rnd_762x39_AK103_bakelite_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK103","","","",{"CUP_30Rnd_762x39_AK103_bakelite_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_762x39_AK103_bakelite_M",4,30}}},{},"CUP_H_Ger_M92_RGR_GG","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Rifleman_RPG_OPF_01 : min_rf_soldier_LAT_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (RPG-7)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CB","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CB","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74_Early","CUP_launch_RPG7V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74_Early","CUP_launch_RPG7V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_PG7V_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_PG7V_M","CUP_30Rnd_545x39_AK_M"};

        backpack = "CUP_B_RPGPack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{"CUP_launch_RPG7V","","","",{"CUP_PG7V_M",1},{},""},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{"CUP_B_RPGPack_Khaki",{{"rhs_rpg7_PG7V_mag",5,1}}},"CUP_H_Ger_M92_RGR_GG_CB","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Grenadier_GP_25_OPF_01 : min_rf_soldier_GL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier (GP-25)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_Ger_M92_RGR","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_Ger_M92_RGR","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK103_GL","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK103_GL","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK103_bakelite_M","CUP_30Rnd_762x39_AK103_bakelite_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK103_bakelite_M","CUP_30Rnd_762x39_AK103_bakelite_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK103_GL","","","",{"CUP_30Rnd_762x39_AK103_bakelite_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_762x39_AK103_bakelite_M",5,30},{"CUP_1Rnd_HE_GP25_M",7,1}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_30Rnd_762x39_AK103_bakelite_M",5,30},{"CUP_1Rnd_HE_GP25_M",5,1},{"CUP_1Rnd_SmokeYellow_GP25_M",5,1},{"CUP_1Rnd_SmokeGreen_GP25_M",5,1},{"CUP_1Rnd_SmokeRed_GP25_M",5,1},{"CUP_1Rnd_SMOKE_GP25_M",5,1},{"CUP_FlareYellow_GP25_M",5,1},{"CUP_FlareRed_GP25_M",3,1},{"CUP_FlareGreen_GP25_M",3,1},{"CUP_FlareWhite_GP25_M",3,1},{"CUP_IlumFlareGreen_GP25_M",3,1},{"CUP_IlumFlareRed_GP25_M",3,1},{"CUP_IlumFlareWhite_GP25_M",3,1}}},"CUP_H_Ger_M92_RGR","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Marksman_SVD_OPF_01 : min_rf_soldier_M_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman (SVD)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_SLA_Boonie","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_SLA_Boonie","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_SVD","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_SVD","Rangefinder"};

        magazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};
        respawnMagazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_10Rnd_762x54_SVD_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_SVD","","","CUP_optic_PSO_3",{"CUP_10Rnd_762x54_SVD_M",10},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_10Rnd_762x54_SVD_M",7,10}}},{},"CUP_H_SLA_Boonie","CUP_G_Grn_Scarf_Shades",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Autorifleman_RPK_OPF_01 : min_rf_soldier_AR_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman (RPK)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_FR_BandanaGreen","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_FR_BandanaGreen","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_RPK74","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_RPK74","Rangefinder"};

        magazines[] = {"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M","CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M"};
        respawnMagazines[] = {"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M","CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_RPK74","","","",{"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",75},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",3,75}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",10,75}}},"CUP_H_FR_BandanaGreen","CUP_FR_NeckScarf",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Machine_Gunner_PKM_OPF_01 : min_rf_soldier_AR_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner (PKM)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_PKM_B50_vfg","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_PKM_B50_vfg","Rangefinder"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_PKM_B50_vfg","","","",{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",100},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"150Rnd_762x54_Box",2,150}}},{"CUP_O_RUS_Patrol_bag_Green",{{"150Rnd_762x54_Box",5,150}}},"CUP_H_Ger_M92_RGR_GG_CF","min_rf_scarf_olive",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Assistant_PKM_Gunner_AKS_74_OPF_01 : O_SLA_Rifleman_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assistant PKM Gunner (AKS-74)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{"CUP_O_RUS_Patrol_bag_Green",{{"150Rnd_762x54_Box",5,150},{"CUP_30Rnd_545x39_AK_M",3,30}}},"CUP_H_Ger_M92_RGR_GG_CF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Medic_AKS_74_OPF_01 : min_rf_medic_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic (AKS-74)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{"CUP_O_RUS_Patrol_bag_Green",{{"ACE_elasticBandage",50},{"ACE_epinephrine",50},{"ACE_morphine",50},{"ACE_tourniquet",4},{"ACE_bloodIV_500",10},{"ACE_bloodIV_250",2},{"ACE_bloodIV",7}}},"CUP_H_Ger_M92_RGR_GG","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Engineer_AKS_74_OPF_01 : min_rf_engineer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer (AKS-74)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_Ger_M92_RGR_GG_CF","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK_M","CUP_30Rnd_545x39_AK_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green_Shovel";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74_Early","","","",{"CUP_30Rnd_545x39_AK_M",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{"CUP_O_RUS_Patrol_bag_Green_Shovel",{{"ACE_DefusalKit",1},{"ACE_Clacker",1},{"ACE_EntrenchingTool",1},{"MineDetector",1},{"SatchelCharge_Remote_Mag",2,1},{"DemoCharge_Remote_Mag",4,1}}},"CUP_H_Ger_M92_RGR_GG_CF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Crewman_AKS_74U_OPF_01 : min_rf_crew_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman (AKS-74U)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_B_USArmy_PilotOverall";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","CUP_H_SLA_TankerHelmet","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","CUP_H_SLA_TankerHelmet","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74U","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"CUP_U_B_USArmy_PilotOverall",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{},"CUP_H_SLA_TankerHelmet","CUP_G_ESS_BLK_Facewrap_Black",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Pilot_AKS_74U_OPF_01 : min_rf_pilot_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot (AKS-74U)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_B_USArmy_PilotOverall";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","CUP_H_RUS_ZSH_Shield_Up","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","CUP_H_RUS_ZSH_Shield_Up","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS74U","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKS74U","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74_plum_M","CUP_30Rnd_545x39_AK74_plum_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS74U","","","",{"CUP_30Rnd_545x39_AK74_plum_M",30},{},""},{},{},{"CUP_U_B_USArmy_PilotOverall",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",2},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rgd5",2,1},{"rhs_mag_rdg2_white",2,1},{"CUP_30Rnd_545x39_AK_M",7,30}}},{},"CUP_H_RUS_ZSH_Shield_Up","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Officer_OPF_01 : min_rf_officer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "U_B_ParadeUniform_01_US_F";

        linkedItems[] = {"RMS37_Beret_SLA","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"RMS37_Beret_SLA","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_M17_Black","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_M17_Black","Rangefinder"};

        magazines[] = {"CUP_21Rnd_9x19_M17_Black","CUP_21Rnd_9x19_M17_Black"};
        respawnMagazines[] = {"CUP_21Rnd_9x19_M17_Black","CUP_21Rnd_9x19_M17_Black"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M17_Black","","","",{"CUP_21Rnd_9x19_M17_Black",21},{},""},{"U_B_ParadeUniform_01_US_F",{{"CUP_17Rnd_9x19_M17_Black",3,17}}},{},{},"RMS37_Beret_SLA","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_General_OPF_01 : O_SLA_Officer_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "General";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Rangemaster","LanguageRUS_F"};

        uniformClass = "U_B_ParadeUniform_01_US_decorated_F";

        linkedItems[] = {"CUP_H_SLA_OfficerCap","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_H_SLA_OfficerCap","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_cz99_etched","Rangefinder"};
        respawnWeapons[] = {"rhs_weap_cz99_etched","Rangefinder"};

        magazines[] = {"rhssaf_mag_15Rnd_9x19_FMJ","rhssaf_mag_15Rnd_9x19_FMJ"};
        respawnMagazines[] = {"rhssaf_mag_15Rnd_9x19_FMJ","rhssaf_mag_15Rnd_9x19_FMJ"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"rhs_weap_cz99_etched","","","",{"rhssaf_mag_15Rnd_9x19_FMJ",15},{},""},{"U_B_ParadeUniform_01_US_decorated_F",{{"rhssaf_mag_15Rnd_9x19_FMJ",3,15}}},{},{},"CUP_H_SLA_OfficerCap","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Arms_Dealer_OPF_01 : O_SLA_Officer_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Arms Dealer";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Orange_EOD","LanguageRUS_F"};

        uniformClass = "U_C_FormalSuit_01_gray_F";

        linkedItems[] = {"H_WirelessEarpiece_F","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_WirelessEarpiece_F","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_Compact","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_Compact","Rangefinder"};

        magazines[] = {"CUP_10Rnd_9x19_Compact","CUP_10Rnd_9x19_Compact"};
        respawnMagazines[] = {"CUP_10Rnd_9x19_Compact","CUP_10Rnd_9x19_Compact"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_Compact","","","",{"CUP_10Rnd_9x19_Compact",10},{},""},{"U_C_FormalSuit_01_gray_F",{{"CUP_10Rnd_9x19_Compact",4,10}}},{},{},"H_WirelessEarpiece_F","G_Aviator",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Propagandist_OPF_01 : O_SLA_General_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Propagandist";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Orange_FIA","LanguageRUS_F"};

        uniformClass = "U_C_FormalSuit_01_tshirt_black_F";

        linkedItems[] = {"RMS37_Beret_SLA","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"RMS37_Beret_SLA","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_M17_Black","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_M17_Black","Rangefinder"};

        magazines[] = {"CUP_21Rnd_9x19_M17_Black","CUP_21Rnd_9x19_M17_Black"};
        respawnMagazines[] = {"CUP_21Rnd_9x19_M17_Black","CUP_21Rnd_9x19_M17_Black"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M17_Black","","","",{"CUP_21Rnd_9x19_M17_Black",21},{},""},{"U_C_FormalSuit_01_tshirt_black_F",{{"CUP_17Rnd_9x19_M17_Black",3,17}}},{},{},"RMS37_Beret_SLA","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Especas_Rifleman_AK_74M_OPF_01 : min_rf_spetsnaz_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Especas Rifleman (AK-74M)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_Green";

        linkedItems[] = {"BRM_RRV_BLACK_RFL","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_RRV_BLACK_RFL","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M_railed_afg","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74M_railed_afg","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M_railed_afg","","","rhsusf_acc_su230a",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_U_O_SLA_Green",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"BRM_RRV_BLACK_RFL",{{"ACE_tourniquet",4},{"SmokeShell",4,1},{"HandGrenade",3,1},{"CUP_30Rnd_545x39_AK74M_M",11,30}}},{},"CUP_H_SLA_Beret","CUP_G_Oakleys_Drk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Especas_Machine_Gunner_PKP_OPF_01 : min_rf_spetsnaz_AR_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Especas Machine Gunner (PKP)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_Green";

        linkedItems[] = {"BRM_RRV_BLACK_MG","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_RRV_BLACK_MG","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_Pecheneg_B50_vfg","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_Pecheneg_B50_vfg","Rangefinder"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M","CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};

        backpack = "CUP_B_USPack_Black";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_Pecheneg_B50_vfg","","","CUP_optic_Kobra",{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",100},{},""},{},{},{"CUP_U_O_SLA_Green",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"BRM_RRV_BLACK_MG",{{"ACE_tourniquet",4},{"SmokeShell",4,1},{"HandGrenade",3,1},{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",2,100}}},{"CUP_B_USPack_Black",{{"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",6,100}}},"CUP_H_SLA_Beret","CUP_G_Oakleys_Drk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Especas_Grenadier_GP_25_OPF_01 : min_rf_spetsnaz_GL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Especas Grenadier (GP-25)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_Green";

        linkedItems[] = {"BRM_RRV_BLACK_GL","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_RRV_BLACK_GL","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M_GL_railed","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74M_GL_railed","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M_GL_railed","","","rhsusf_acc_su230a",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_U_O_SLA_Green",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"BRM_RRV_BLACK_GL",{{"ACE_tourniquet",4},{"SmokeShell",4,1},{"HandGrenade",3,1},{"CUP_30Rnd_545x39_AK74M_M",8,30},{"CUP_1Rnd_HE_GP25_M",8,1}}},{},"CUP_H_SLA_Beret","CUP_G_Oakleys_Drk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Especas_Marksman_L115_OPF_01 : min_rf_spetsnaz_M_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Especas Marksman (L115)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_Green";

        linkedItems[] = {"BRM_RRV_BLACK_REC1","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_RRV_BLACK_REC1","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_AWM_wdl","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_AWM_wdl","Rangefinder"};

        magazines[] = {"CUP_5Rnd_86x70_L115A1","CUP_5Rnd_86x70_L115A1"};
        respawnMagazines[] = {"CUP_5Rnd_86x70_L115A1","CUP_5Rnd_86x70_L115A1"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_AWM_wdl","","","CUP_optic_LeupoldM3LR",{"CUP_5Rnd_86x70_L115A1",5},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"CUP_U_O_SLA_Green",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"BRM_RRV_BLACK_REC1",{{"ACE_tourniquet",4},{"SmokeShell",4,1},{"HandGrenade",3,1},{"CUP_5Rnd_86x70_L115A1",16,5}}},{},"CUP_H_SLA_Beret","CUP_G_Oakleys_Drk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Especas_Medic_AK_74M_OPF_01 : min_rf_recon_medic_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Especas Medic (AK-74M)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_Green";

        linkedItems[] = {"BRM_RRV_BLACK_MED","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"BRM_RRV_BLACK_MED","CUP_H_SLA_Beret","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M_railed_afg","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74M_railed_afg","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        backpack = "CUP_B_USPack_Black";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M_railed_afg","","","rhsusf_acc_su230a",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_U_O_SLA_Green",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"BRM_RRV_BLACK_MED",{{"ACE_tourniquet",4},{"SmokeShell",4,1},{"HandGrenade",3,1},{"CUP_30Rnd_545x39_AK74M_M",11,30}}},{"CUP_B_USPack_Black",{{"ACE_tourniquet",5},{"ACE_morphine",50},{"ACE_epinephrine",50},{"ACE_elasticBandage",50},{"ACE_bloodIV_500",10},{"ACE_bloodIV",7},{"ACE_bloodIV_250",2}}},"CUP_H_SLA_Beret","CUP_G_Oakleys_Drk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_SLA_Field_Officer_PP_19_OPF_01 : O_SLA_Officer_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Field Officer (PP-19)";
        side = 0;
        faction = "O_SLA_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_O_SLA_MixedCamo";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","RMS37_Beret_SLA","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","RMS37_Beret_SLA","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_vityaz","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_vityaz","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19AP_Vityaz","CUP_30Rnd_9x19AP_Vityaz"};
        respawnMagazines[] = {"CUP_30Rnd_9x19AP_Vityaz","CUP_30Rnd_9x19AP_Vityaz"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_vityaz","","","",{"CUP_30Rnd_9x19AP_Vityaz",30},{},""},{},{},{"CUP_U_O_SLA_MixedCamo",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhs_mag_rdg2_white",2,1},{"rhs_mag_rgd5",2,1},{"CUP_30Rnd_9x19_Vityaz",5,30},{"CUP_10Rnd_9x19_Saiga9",2,10}}},{},"RMS37_Beret_SLA","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};