//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_CAFWIN_IND {
        displayName = "Chernarussian Armed Forces (Winter)";
        side = 2;
        flag = "\ca\data\flag_chernarus_co.paa";
        icon = "\ca\data\flag_chernarus_co.paa";
        priority = 0;
    };
};