//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class CUP_B_CZ_Soldier_805_WDL;
    class CUP_B_CZ_Soldier_805_WDL_OCimport_01 : CUP_B_CZ_Soldier_805_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Soldier_805_WDL_OCimport_02 : CUP_B_CZ_Soldier_805_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Soldier_WDL;
    class CUP_B_CZ_Soldier_WDL_OCimport_01 : CUP_B_CZ_Soldier_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Soldier_WDL_OCimport_02 : CUP_B_CZ_Soldier_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Soldier_AT_WDL;
    class CUP_B_CZ_Soldier_AT_WDL_OCimport_01 : CUP_B_CZ_Soldier_AT_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Soldier_AT_WDL_OCimport_02 : CUP_B_CZ_Soldier_AT_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Soldier_SL_WDL;
    class CUP_B_CZ_Soldier_SL_WDL_OCimport_01 : CUP_B_CZ_Soldier_SL_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Soldier_SL_WDL_OCimport_02 : CUP_B_CZ_Soldier_SL_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Soldier_Marksman_WDL;
    class CUP_B_CZ_Soldier_Marksman_WDL_OCimport_01 : CUP_B_CZ_Soldier_Marksman_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Soldier_Marksman_WDL_OCimport_02 : CUP_B_CZ_Soldier_Marksman_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Soldier_AR_WDL;
    class CUP_B_CZ_Soldier_AR_WDL_OCimport_01 : CUP_B_CZ_Soldier_AR_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Soldier_AR_WDL_OCimport_02 : CUP_B_CZ_Soldier_AR_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Medic_WDL;
    class CUP_B_CZ_Medic_WDL_OCimport_01 : CUP_B_CZ_Medic_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Medic_WDL_OCimport_02 : CUP_B_CZ_Medic_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Engineer_WDL;
    class CUP_B_CZ_Engineer_WDL_OCimport_01 : CUP_B_CZ_Engineer_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Engineer_WDL_OCimport_02 : CUP_B_CZ_Engineer_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Crew_WDL;
    class CUP_B_CZ_Crew_WDL_OCimport_01 : CUP_B_CZ_Crew_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Crew_WDL_OCimport_02 : CUP_B_CZ_Crew_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Pilot_WDL;
    class CUP_B_CZ_Pilot_WDL_OCimport_01 : CUP_B_CZ_Pilot_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Pilot_WDL_OCimport_02 : CUP_B_CZ_Pilot_WDL_OCimport_01 { class EventHandlers; };

    class CUP_B_CZ_Officer_WDL;
    class CUP_B_CZ_Officer_WDL_OCimport_01 : CUP_B_CZ_Officer_WDL { scope = 0; class EventHandlers; };
    class CUP_B_CZ_Officer_WDL_OCimport_02 : CUP_B_CZ_Officer_WDL_OCimport_01 { class EventHandlers; };


    class I_CAFWDL_Rifleman_CZ805_IND_01 : CUP_B_CZ_Soldier_805_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (CZ805)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_CZ805_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_CZ805_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_CZ805_A1","","","",{"CUP_30Rnd_556x45_CZ805",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_556x45_CZ805",6,30}}},{},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Rifleman_CZ805_IND_01 : I_CAFWDL_Rifleman_CZ805_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (CZ805)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_CZ805_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_CZ805_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_CZ805_A1","","","",{"CUP_30Rnd_556x45_CZ805",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_556x45_CZ805",6,30}}},{},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Rifleman_Vz58P_IND_01 : CUP_B_CZ_Soldier_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Vz58P)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58P","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58P","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58P","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Rifleman_Vz58P_IND_01 : I_CAFWDL_Rifleman_Vz58P_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Vz58P)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58P","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58P","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58P","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Rifleman_RPG7_IND_01 : CUP_B_CZ_Soldier_AT_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (RPG7)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58P","CUP_launch_RPG7V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58P","CUP_launch_RPG7V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_PG7V_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_PG7V_M","CUP_30Rnd_Sa58_M"};

        backpack = "CUP_B_RPGPack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58P","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{"CUP_launch_RPG7V","","","",{"CUP_PG7V_M",1},{},""},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{"CUP_B_RPGPack_Khaki",{{"rhs_rpg7_PG7V_mag",5,1}}},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Rifleman_RPG7_IND_01 : I_CAFWDL_Rifleman_RPG7_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (RPG7)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58P","CUP_launch_RPG7V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58P","CUP_launch_RPG7V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_PG7V_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_PG7V_M","CUP_30Rnd_Sa58_M"};

        backpack = "CUP_B_RPGPack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58P","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{"CUP_launch_RPG7V","","","",{"CUP_PG7V_M",1},{},""},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{"CUP_B_RPGPack_Khaki",{{"rhs_rpg7_PG7V_mag",5,1}}},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Squad_Leader_G805_IND_01 : CUP_B_CZ_Soldier_SL_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader (G805)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_CZ805_GL","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_CZ805_GL","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_CZ805_GL","","","",{"CUP_30Rnd_556x45_CZ805",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_556x45_CZ805",8,30},{"CUP_1Rnd_HE_M203",6,1}}},{},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Squad_Leader_G805_IND_01 : I_CAFWDL_Squad_Leader_G805_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader (G805)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_CZ805_GL","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_CZ805_GL","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_CZ805","CUP_30Rnd_556x45_CZ805"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_CZ805_GL","","","",{"CUP_30Rnd_556x45_CZ805",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_556x45_CZ805",8,30},{"CUP_1Rnd_HE_M203",6,1}}},{},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Marksman_CZ750_IND_01 : CUP_B_CZ_Soldier_Marksman_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman (CZ750)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_CDF_OfficerCap_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_CDF_OfficerCap_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_CZ750","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_CZ750","Rangefinder"};

        magazines[] = {"CUP_10Rnd_762x51_CZ750_Tracer","CUP_10Rnd_762x51_CZ750_Tracer"};
        respawnMagazines[] = {"CUP_10Rnd_762x51_CZ750_Tracer","CUP_10Rnd_762x51_CZ750_Tracer"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_CZ750","","","CUP_optic_LeupoldM3LR",{"CUP_10Rnd_762x51_CZ750_Tracer",10},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_10Rnd_762x51_CZ750",6,10}}},{},"CUP_H_CDF_OfficerCap_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Marksman_CZ750_IND_01 : I_CAFWDL_Marksman_CZ750_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman (CZ750)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Grey","CUP_H_CDF_OfficerCap_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Grey","CUP_H_CDF_OfficerCap_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_CZ750","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_CZ750","Rangefinder"};

        magazines[] = {"CUP_10Rnd_762x51_CZ750_Tracer","CUP_10Rnd_762x51_CZ750_Tracer"};
        respawnMagazines[] = {"CUP_10Rnd_762x51_CZ750_Tracer","CUP_10Rnd_762x51_CZ750_Tracer"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_CZ750","","","CUP_optic_LeupoldM3LR",{"CUP_10Rnd_762x51_CZ750_Tracer",10},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_10Rnd_762x51_CZ750",6,10}}},{},"CUP_H_CDF_OfficerCap_SNW","G_Bandanna_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Autorifleman_M249_IND_01 : CUP_B_CZ_Soldier_AR_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman (M249)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_M249_E2","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_M249_E2","Rangefinder"};

        magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
        respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_M249_E2","","","",{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",200},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",2,200}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",7,200}}},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Autorifleman_M249_IND_01 : I_CAFWDL_Autorifleman_M249_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman (M249)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Grenadier_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_M249_E2","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_M249_E2","Rangefinder"};

        magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
        respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};

        backpack = "CUP_O_RUS_Patrol_bag_Winter";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_M249_E2","","","",{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",200},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Grenadier_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",2,200}}},{"CUP_O_RUS_Patrol_bag_Winter",{{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",7,200}}},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Medic_Vz58V_IND_01 : CUP_B_CZ_Medic_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic (Vz58V)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{"CUP_O_RUS_Patrol_bag_Green",{{"ACE_epinephrine",50},{"ACE_elasticBandage",50},{"ACE_morphine",50},{"ACE_tourniquet",5},{"ACE_bloodIV_500",10},{"ACE_bloodIV",7},{"ACE_bloodIV_250",2}}},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Medic_Vz58V_IND_01 : I_CAFWDL_Medic_Vz58V_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic (Vz58V)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Winter";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{"CUP_O_RUS_Patrol_bag_Winter",{{"ACE_epinephrine",50},{"ACE_elasticBandage",50},{"ACE_morphine",50},{"ACE_tourniquet",5},{"ACE_bloodIV_500",10},{"ACE_bloodIV",7},{"ACE_bloodIV_250",2}}},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Engineer_Vz58V_IND_01 : CUP_B_CZ_Engineer_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer (Vz58V)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","CUP_H_CDF_H_PASGT_FST","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green_Shovel";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{"CUP_O_RUS_Patrol_bag_Green_Shovel",{{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_Clacker",1},{"MineDetector",1},{"SatchelCharge_Remote_Mag",2,1},{"DemoCharge_Remote_Mag",4,1}}},"CUP_H_CDF_H_PASGT_FST","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Engineer_Vz58V_IND_01 : I_CAFWDL_Engineer_Vz58V_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer (Vz58V)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","CUP_H_CDF_H_PASGT_SNW","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Winter";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{"CUP_O_RUS_Patrol_bag_Winter",{{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_Clacker",1},{"MineDetector",1},{"SatchelCharge_Remote_Mag",2,1},{"DemoCharge_Remote_Mag",4,1}}},"CUP_H_CDF_H_PASGT_SNW","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Crewman_EVO3_IND_01 : CUP_B_CZ_Crew_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman (EVO3)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","CUP_H_SLA_TankerHelmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","CUP_H_SLA_TankerHelmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"CUP_H_SLA_TankerHelmet","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Crewman_EVO3_IND_01 : I_CAFWDL_Crewman_EVO3_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman (EVO3)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","CUP_H_SLA_TankerHelmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","CUP_H_SLA_TankerHelmet","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"CUP_H_SLA_TankerHelmet","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Pilot_EVO3_IND_01 : CUP_B_CZ_Pilot_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot (EVO3)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","rhs_zsh7a_mike_green_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","rhs_zsh7a_mike_green_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"rhs_zsh7a_mike_green_alt","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Pilot_EVO3_IND_01 : I_CAFWDL_Pilot_EVO3_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot (EVO3)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","rhs_zsh7a_mike_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","rhs_zsh7a_mike_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"rhs_zsh7a_mike_alt","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Jet_Pilot_EVO3_IND_01 : CUP_B_CZ_Pilot_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Jet Pilot (EVO3)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","rhs_zsh7a_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","rhs_zsh7a_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"rhs_zsh7a_alt","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Jet_Pilot_EVO3_IND_01 : I_CAFWDL_Jet_Pilot_EVO3_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Jet Pilot (EVO3)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","rhs_zsh7a_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","rhs_zsh7a_alt","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"rhs_zsh7a_alt","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Infantry_Officer_Vz58V_IND_01 : CUP_B_CZ_Officer_WDL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Infantry Officer (Vz58V)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Infantry_Officer_Vz58V_IND_01 : I_CAFWDL_Infantry_Officer_Vz58V_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Infantry Officer (Vz58V)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Field_Commander_Vz58V_IND_01 : I_CAFWDL_Infantry_Officer_Vz58V_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Field Commander (Vz58V)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Orange_Officer","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Field_Commander_Vz58V_IND_01 : I_CAFWDL_Field_Commander_Vz58V_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Field Commander (Vz58V)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Orange_Officer","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Rifleman_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Sa58V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Sa58V","Rangefinder"};

        magazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};
        respawnMagazines[] = {"CUP_30Rnd_Sa58_M","CUP_30Rnd_Sa58_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Sa58V","","","",{"CUP_30Rnd_Sa58_M",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Rifleman_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_Sa58_M",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Armored_Commander_EVO3_IND_01 : I_CAFWDL_Field_Commander_Vz58V_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Armored Commander (EVO3)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Orange_Civilian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Armored_Commander_EVO3_IND_01 : I_CAFWDL_Armored_Commander_EVO3_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Armored Commander (EVO3)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Orange_Civilian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWDL_Air_Force_Officer_EVO3_IND_01 : I_CAFWDL_Armored_Commander_EVO3_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Air Force Officer (EVO3)";
        side = 2;
        faction = "I_CAFWDL_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_FST_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Olive","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_FST_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Olive",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_CAFWIN_Air_Force_Officer_EVO3_IND_01 : I_CAFWDL_Air_Force_Officer_EVO3_IND_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Air Force Officer (EVO3)";
        side = 2;
        faction = "I_CAFWIN_IND";

        identityTypes[] = {"Head_Russian","CUP_D_Language_CZ_ACR","CUP_G_ARMY"};

        uniformClass = "CUP_U_B_CDF_SNW_2";

        linkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_Interceptor_Base_Grey","RMS37_Beret_CAF","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_U_B_CDF_SNW_2",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_B_Interceptor_Base_Grey",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"SmokeShell",5,1},{"HandGrenade",2,1},{"CUP_30Rnd_9x19_EVO",5,30}}},{},"RMS37_Beret_CAF","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};