//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_NCO_OPF {
        displayName = "New Central Order";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\Poland_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Poland_ca.paa";
        priority = 0;
    };
};