//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 202.147284 on Stable branch
// Generated with ALiVE version 1.13.2.2102061
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class min_rf_soldier;
    class min_rf_soldier_OCimport_01 : min_rf_soldier { scope = 0; class EventHandlers; };
    class min_rf_soldier_OCimport_02 : min_rf_soldier_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_LAT;
    class min_rf_soldier_LAT_OCimport_01 : min_rf_soldier_LAT { scope = 0; class EventHandlers; };
    class min_rf_soldier_LAT_OCimport_02 : min_rf_soldier_LAT_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_GL;
    class min_rf_soldier_GL_OCimport_01 : min_rf_soldier_GL { scope = 0; class EventHandlers; };
    class min_rf_soldier_GL_OCimport_02 : min_rf_soldier_GL_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_M;
    class min_rf_soldier_M_OCimport_01 : min_rf_soldier_M { scope = 0; class EventHandlers; };
    class min_rf_soldier_M_OCimport_02 : min_rf_soldier_M_OCimport_01 { class EventHandlers; };

    class min_rf_soldier_AR;
    class min_rf_soldier_AR_OCimport_01 : min_rf_soldier_AR { scope = 0; class EventHandlers; };
    class min_rf_soldier_AR_OCimport_02 : min_rf_soldier_AR_OCimport_01 { class EventHandlers; };

    class min_rf_medic;
    class min_rf_medic_OCimport_01 : min_rf_medic { scope = 0; class EventHandlers; };
    class min_rf_medic_OCimport_02 : min_rf_medic_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_rifleman;
    class rhsgref_ins_rifleman_OCimport_01 : rhsgref_ins_rifleman { scope = 0; class EventHandlers; };
    class rhsgref_ins_rifleman_OCimport_02 : rhsgref_ins_rifleman_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_saboteur;
    class rhsgref_ins_saboteur_OCimport_01 : rhsgref_ins_saboteur { scope = 0; class EventHandlers; };
    class rhsgref_ins_saboteur_OCimport_02 : rhsgref_ins_saboteur_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_squadleader;
    class rhsgref_ins_squadleader_OCimport_01 : rhsgref_ins_squadleader { scope = 0; class EventHandlers; };
    class rhsgref_ins_squadleader_OCimport_02 : rhsgref_ins_squadleader_OCimport_01 { class EventHandlers; };

    class min_rf_pilot;
    class min_rf_pilot_OCimport_01 : min_rf_pilot { scope = 0; class EventHandlers; };
    class min_rf_pilot_OCimport_02 : min_rf_pilot_OCimport_01 { class EventHandlers; };

    class CUP_O_sla_Soldier_militia;
    class CUP_O_sla_Soldier_militia_OCimport_01 : CUP_O_sla_Soldier_militia { scope = 0; class EventHandlers; };
    class CUP_O_sla_Soldier_militia_OCimport_02 : CUP_O_sla_Soldier_militia_OCimport_01 { class EventHandlers; };

    class CUP_O_sla_Officer_militia;
    class CUP_O_sla_Officer_militia_OCimport_01 : CUP_O_sla_Officer_militia { scope = 0; class EventHandlers; };
    class CUP_O_sla_Officer_militia_OCimport_02 : CUP_O_sla_Officer_militia_OCimport_01 { class EventHandlers; };

    class min_rf_recon_officer;
    class min_rf_recon_officer_OCimport_01 : min_rf_recon_officer { scope = 0; class EventHandlers; };
    class min_rf_recon_officer_OCimport_02 : min_rf_recon_officer_OCimport_01 { class EventHandlers; };

    class min_rf_recon;
    class min_rf_recon_OCimport_01 : min_rf_recon { scope = 0; class EventHandlers; };
    class min_rf_recon_OCimport_02 : min_rf_recon_OCimport_01 { class EventHandlers; };


    class O_LGN_Soldado_AKM_OPF_01 : min_rf_soldier_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Soldado (AKM)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_13";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_US_patrol_cap_Tpattern","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_US_patrol_cap_Tpattern","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","Rangefinder"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_bakelite_M",30},{},""},{},{},{"CUP_I_B_PMC_Unit_13",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_30Rnd_762x39_AK47_bakelite_M",8,30}}},{},"CUP_H_US_patrol_cap_Tpattern","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Soldado_AUGA1_OPF_01 : O_LGN_Soldado_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Soldado (AUGA1)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_16";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_FR_BandanaGreen","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_FR_BandanaGreen","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AUG_A1","","","",{"CUP_30Rnd_556x45_AUG",30},{},""},{},{},{"CUP_I_B_PMC_Unit_16",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_30Rnd_556x45_AUG",10,30}}},{},"CUP_H_FR_BandanaGreen","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Soldado_FAL_OPF_01 : O_LGN_Soldado_AKM_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Soldado (FAL)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_20";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_USA_Boonie_wdl","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_USA_Boonie_wdl","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_FNFAL5061","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5061","Rangefinder"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","CUP_20Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","CUP_20Rnd_762x51_FNFAL_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5061","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_I_B_PMC_Unit_20",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_20Rnd_762x51_FNFAL_M",6,20}}},{},"CUP_H_USA_Boonie_wdl","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Sicario_RPG_OPF_01 : min_rf_soldier_LAT_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sicario (RPG-7)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_17";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","H_Watchcap_blk","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","H_Watchcap_blk","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Galil_black","CUP_launch_RPG7V","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Galil_black","CUP_launch_RPG7V","Rangefinder"};

        magazines[] = {"CUP_25Rnd_762x51_Galil_Mag","CUP_PG7V_M","CUP_25Rnd_762x51_Galil_Mag"};
        respawnMagazines[] = {"CUP_25Rnd_762x51_Galil_Mag","CUP_PG7V_M","CUP_25Rnd_762x51_Galil_Mag"};

        backpack = "CUP_B_RPGPack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Galil_black","","","",{"CUP_25Rnd_762x51_Galil_Mag",25},{},""},{"CUP_launch_RPG7V","","","",{"CUP_PG7V_M",1},{},""},{},{"CUP_I_B_PMC_Unit_17",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_25Rnd_762x51_Galil_Mag",7,25}}},{"CUP_B_RPGPack_Khaki",{{"rhs_rpg7_PG7V_mag",5,1}}},"H_Watchcap_blk","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Sicario_EGLM_OPF_01 : min_rf_soldier_GL_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sicario (EGLM)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_17";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","H_Bandanna_gry","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","H_Bandanna_gry","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Mk16_CQC_EGLM_black","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Mk16_CQC_EGLM_black","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag_Mk16_black","CUP_30Rnd_556x45_Stanag_Mk16_black"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag_Mk16_black","CUP_30Rnd_556x45_Stanag_Mk16_black"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Mk16_CQC_EGLM_black","","","",{"CUP_30Rnd_556x45_Stanag_Mk16_black",30},{},""},{},{},{"CUP_I_B_PMC_Unit_17",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_30Rnd_556x45_Stanag_Mk16_black",7,30},{"CUP_1Rnd_HE_M203",6,1}}},{},"H_Bandanna_gry","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Sicario_SR_25_OPF_01 : min_rf_soldier_M_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sicario (SR-25)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_17";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","H_Cap_blk","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","H_Cap_blk","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_m110_kac_black","Rangefinder"};
        respawnWeapons[] = {"CUP_srifle_m110_kac_black","Rangefinder"};

        magazines[] = {"CUP_20Rnd_762x51_B_M110","CUP_20Rnd_762x51_B_M110"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_B_M110","CUP_20Rnd_762x51_B_M110"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_m110_kac_black","CUP_muzzle_snds_M110_black","","CUP_optic_LeupoldM3LR",{"CUP_20Rnd_762x51_B_M110",20},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"CUP_I_B_PMC_Unit_17",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1},{"CUP_20Rnd_762x51_B_M110",1,20}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_20Rnd_762x51_B_M110",5,20}}},{},"H_Cap_blk","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Sicario_M249_OPF_01 : min_rf_soldier_AR_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sicario (M249)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_17";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_m249_para","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_m249_para","Rangefinder"};

        magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
        respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_m249_para","","","",{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",200},{},""},{},{},{"CUP_I_B_PMC_Unit_17",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",2,200}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",7,200}}},"","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_El_Doctor_OPF_01 : min_rf_medic_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "El Doctor";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_U_C_Labcoat_01";

        linkedItems[] = {"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_hgun_M17_Black","Rangefinder"};
        respawnWeapons[] = {"CUP_hgun_M17_Black","Rangefinder"};

        magazines[] = {"CUP_17Rnd_9x19_M17_Black","CUP_17Rnd_9x19_M17_Black"};
        respawnMagazines[] = {"CUP_17Rnd_9x19_M17_Black","CUP_17Rnd_9x19_M17_Black"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M17_Black","","","",{"CUP_17Rnd_9x19_M17_Black",17},{},""},{"CUP_U_C_Labcoat_01",{{"CUP_17Rnd_9x19_M17_Black",3,17}}},{},{},"","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_El_Jefe_OPF_01 : O_LGN_El_Doctor_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "El Jefe";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Orange_FIA","LanguageRUS_F"};

        uniformClass = "U_C_FormalSuit_01_tshirt_black_F";

        linkedItems[] = {"CUP_V_B_LBT_LBV_Black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_LBT_LBV_Black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A1GL","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_M16A1GL","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1GL","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"U_C_FormalSuit_01_tshirt_black_F",{{"ACE_personalAidKit",1},{"ACE_morphine",5},{"ACE_elasticBandage",5}}},{"CUP_V_B_LBT_LBV_Black",{{"ACE_tourniquet",5},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",4,1},{"CUP_1Rnd_HE_M203",5,1},{"CUP_30Rnd_556x45_Stanag",6,30}}},{},"","G_Aviator",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_El_Buchon_OPF_01 : O_LGN_El_Doctor_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "El Buchon";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_17";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_PMC_Cap_Back_PRR_Grey","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_PMC_Cap_Back_PRR_Grey","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AK74M_GL_railed","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AK74M_GL_railed","Rangefinder"};

        magazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};
        respawnMagazines[] = {"CUP_30Rnd_545x39_AK74M_M","CUP_30Rnd_545x39_AK74M_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AK74M_GL_railed","","","",{"CUP_30Rnd_545x39_AK74M_M",30},{},""},{},{},{"CUP_I_B_PMC_Unit_17",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1},{"CUP_30Rnd_545x39_AK74M_M",2,30},{"CUP_1Rnd_HE_GP25_M",1,1}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_30Rnd_545x39_AK74M_M",7,30},{"CUP_1Rnd_HE_GP25_M",6,1}}},{},"CUP_H_PMC_Cap_Back_PRR_Grey","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Coca_Farmer_AUGA1_OPF_01 : rhsgref_ins_rifleman_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Coca Farmer (AUGA1)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "U_C_Uniform_Farmer_01_F";

        linkedItems[] = {"V_TacChestrig_oli_F","CUP_H_NAPA_Fedora","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_oli_F","CUP_H_NAPA_Fedora","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AUG_A1","","","",{"CUP_30Rnd_556x45_AUG",30},{},""},{},{},{"U_C_Uniform_Farmer_01_F",{{"ACE_elasticBandage",5},{"ACE_personalAidKit",1},{"ACE_morphine",5}}},{"V_TacChestrig_oli_F",{{"ACE_tourniquet",4},{"ACE_morphine",10},{"ACE_epinephrine",15},{"ACE_elasticBandage",10},{"CUP_30Rnd_556x45_AUG",12,30}}},{},"CUP_H_NAPA_Fedora","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Drug_Lab_Worker_Galil_OPF_01 : rhsgref_ins_saboteur_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Drug Lab Worker (Galil)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_Winter_M81";

        linkedItems[] = {"V_TacChestrig_oli_F","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_oli_F","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Galil_SAR_black","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_Galil_SAR_black","Rangefinder"};

        magazines[] = {"CUP_35Rnd_556x45_Galil_Mag","CUP_35Rnd_556x45_Galil_Mag"};
        respawnMagazines[] = {"CUP_35Rnd_556x45_Galil_Mag","CUP_35Rnd_556x45_Galil_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Galil_SAR_black","","","",{"CUP_35Rnd_556x45_Galil_Mag",35},{},""},{},{},{"CUP_U_B_BDUv2_gloves_dirty_Winter_M81",{{"ACE_elasticBandage",5},{"ACE_personalAidKit",1},{"ACE_morphine",5},{"CUP_35Rnd_556x45_Galil_Mag",2,35}}},{"V_TacChestrig_oli_F",{{"ACE_tourniquet",4},{"ACE_morphine",10},{"ACE_epinephrine",15},{"ACE_elasticBandage",10},{"CUP_35Rnd_556x45_Galil_Mag",11,35}}},{},"","G_Respirator_white_F",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Production_Chief_FAL_OPF_01 : rhsgref_ins_squadleader_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Production Chief (FAL)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Orange_Officer","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "CUP_I_B_PMC_Unit_20";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","PMC_Cap_Backwards_Dark","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","PMC_Cap_Backwards_Dark","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_FNFAL_OSW","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_FNFAL_OSW","Rangefinder"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","CUP_20Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","CUP_20Rnd_762x51_FNFAL_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL_OSW","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_I_B_PMC_Unit_20",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_20Rnd_762x51_FNFAL_M",6,20}}},{},"PMC_Cap_Backwards_Dark","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Cartel_Pilot_EVO3_OPF_01 : min_rf_pilot_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Cartel Pilot (EVO3)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageRUS_F"};

        uniformClass = "CUP_I_B_PMC_Unit_17";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","rhsusf_hgu56p_visor_black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","rhsusf_hgu56p_visor_black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_EVO","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_EVO","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_EVO","CUP_30Rnd_9x19_EVO"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_EVO","","","",{"CUP_30Rnd_9x19_EVO",30},{},""},{},{},{"CUP_I_B_PMC_Unit_17",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1},{"CUP_30Rnd_9x19_EVO",2,30}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_30Rnd_9x19_EVO",8,30}}},{},"rhsusf_hgu56p_visor_black","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Smuggler_MP5_OPF_01 : CUP_O_sla_Soldier_militia_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Smuggler (MP5)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_TK","LanguageGRE_F"};

        uniformClass = "CUP_I_B_PMC_Unit_24";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_PMC_Beanie_Headphones_Black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_PMC_Beanie_Headphones_Black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_smg_MP5A5","Rangefinder"};
        respawnWeapons[] = {"CUP_smg_MP5A5","Rangefinder"};

        magazines[] = {"CUP_30Rnd_9x19_MP5","CUP_30Rnd_9x19_MP5"};
        respawnMagazines[] = {"CUP_30Rnd_9x19_MP5","CUP_30Rnd_9x19_MP5"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_smg_MP5A5","","","",{"CUP_30Rnd_9x19_MP5",30},{},""},{},{},{"CUP_I_B_PMC_Unit_24",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"HandGrenade",3,1},{"CUP_30Rnd_9x19_MP5",8,30}}},{},"CUP_H_PMC_Beanie_Headphones_Black","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Smuggle_Overseer_OPF_01 : CUP_O_sla_Officer_militia_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Smuggle Overseer";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Orange_AAF","LanguageGRE_F"};

        uniformClass = "CUP_I_B_PMC_Unit_24";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Gren","CUP_H_Ger_M92_Black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Gren","CUP_H_Ger_M92_Black","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_M60","Rangefinder"};
        respawnWeapons[] = {"CUP_lmg_M60","Rangefinder"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};

        backpack = "min_rf_torna_black";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_M60","","","",{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",100},{},""},{},{},{"CUP_I_B_PMC_Unit_24",{{"ACE_elasticBandage",16},{"ACE_epinephrine",10},{"ACE_morphine",16},{"ACE_personalAidKit",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_tourniquet",4}}},{"CUP_V_PMC_IOTV_Black_Gren",{{"HandGrenade",3,1},{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",2,100}}},{"min_rf_torna_black",{{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",7,100}}},"CUP_H_Ger_M92_Black","CUP_G_ESS_RGR_Facewrap_Skull",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Mercenary_Advisor_OPF_01 : min_rf_recon_officer_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary Advisor";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"SMG_03C_black","Rangefinder"};
        respawnWeapons[] = {"SMG_03C_black","Rangefinder"};

        magazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};
        respawnMagazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};

        ALiVE_orbatCreator_loadout[] = {{"SMG_03C_black","","","",{"50Rnd_570x28_SMG_03",50},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"50Rnd_570x28_SMG_03",6,50}}},{},"RMS37_Beret_Clawhammer","CUP_FR_NeckScarf3",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Mercenary_Dealer_OPF_01 : O_LGN_Mercenary_Advisor_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary Dealer";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","RMS37_Beret_Clawhammer","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AUG_A1","","","",{"CUP_30Rnd_556x45_AUG",30},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"CUP_30Rnd_556x45_AUG",9,30}}},{},"RMS37_Beret_Clawhammer","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Mercenary_AUGA1_OPF_01 : min_rf_recon_OCimport_02 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary (AUGA1)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Patrol","BRM_LWH_COMS_BLACK","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};
        respawnWeapons[] = {"CUP_arifle_AUG_A1","Rangefinder"};

        magazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_AUG","CUP_30Rnd_556x45_AUG"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AUG_A1","","","",{"CUP_30Rnd_556x45_AUG",30},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Patrol",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"CUP_30Rnd_556x45_AUG",9,30}}},{},"BRM_LWH_COMS_BLACK","CUP_G_ESS_BLK_Scarf_Face_Blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_LGN_Mercenary_Pilot_FN_P90_OPF_01 : O_LGN_Mercenary_AUGA1_OPF_01 {
        author = "Tempestus";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary Pilot (FN P90)";
        side = 0;
        faction = "O_LGN_OPF";

        identityTypes[] = {"Head_Euro","LanguageRUS_F"};

        uniformClass = "CUP_U_CRYE_G3C_BLK";

        linkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","rhsusf_hgu56p_visor_black","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_PMC_IOTV_Black_Empty","rhsusf_hgu56p_visor_black","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch"};

        weapons[] = {"SMG_03C_black","Rangefinder"};
        respawnWeapons[] = {"SMG_03C_black","Rangefinder"};

        magazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};
        respawnMagazines[] = {"50Rnd_570x28_SMG_03","50Rnd_570x28_SMG_03"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"SMG_03C_black","","","",{"50Rnd_570x28_SMG_03",50},{},""},{},{},{"CUP_U_CRYE_G3C_BLK",{{"ACE_elasticBandage",10},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_personalAidKit",1}}},{"CUP_V_PMC_IOTV_Black_Empty",{{"ACE_tourniquet",4},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"HandGrenade",2,1},{"SmokeShell",5,1},{"50Rnd_570x28_SMG_03",1,50}}},{"B_LegStrapBag_black_F",{{"50Rnd_570x28_SMG_03",6,50}}},"rhsusf_hgu56p_visor_black","CUP_RUS_Balaclava_blk",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};